### ISSUE TITLE
Ensure that the conda environment is portable

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect-intel#13]
The included conda environment at https://github.com/PrefectHQ/prefect-intel/blob/main/conda-environment.yaml is usable across Prefect internal machines which are all running macOS. We must confirm that this install is usable across Intel development environments as well.

The requirements generated by exporting the environment may be overly constrained.

**Comment by serinamarie** [comment]
Hi Michael,
The CS team at Prefect has been investigating this and other Windows compatibility issues for this repo. A modification of the conda-environment.yaml to:
```yaml
name: prefect-intel
channels:
  - defaults
dependencies:
  - ca-certificates=2022.3
  - certifi=2021.10.8
  - openssl=1.1
  - pip=21.2.4
  - python=3.9
  - setuptools=61.2
  - sqlite=3.38
  - tk=8.6
  - tzdata=2022a
  - wheel=0.37
  - xz=5.2
  - zlib=1.2
  - pip:
    - -e ./prefect
```

has shown to be portable from macOS to Windows. As you can see above, the patches and builds are unspecified, so that the exported environment is not overly constrained, as you mentioned. Platform-specific dependencies for macOS have also been removed from this (libffi, libcxx, ncurses, readline) as they are installed when Python is.
